name: AkatsukiRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка Ngrok.
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -O ngrok.zip
        wget https://raw.githubusercontent.com/gamegame1236/dedic-top/main/start.bat -O start.bat
        wget https://raw.githubusercontent.com/gamegame1236/dedic-top/main/loop.bat -O loop.bat
    - name: Загрузка программ.
      run: |
        wget https://raw.githubusercontent.com/gamegame1236/dedic-top/main/launcher/Node.js.lnk -O Node.js.lnk
        wget https://raw.githubusercontent.com/gamegame1236/dedic-top/main/launcher/FastConfigVPS_v2.3.exe -O "FastConfigVPS_v2.3.exe"
        wget https://raw.githubusercontent.com/gamegame1236/dedic-top/main/launcher/Visual%20Studio%202019.lnk -O "Visual Studio 2019.lnk"
        apt-get install unzip
    - name: Загрузка Ngrok файла.
      run: unzip ngrok.zip
    - name: Подключение к учётной записи Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Подключение к CPU 2 - 7 ГБ оперативной памяти - 256 SSD.
      run: cmd /c start.bat
    - name: Сделано успешно! Вы можете закрыть вкладку.
      run: cmd /c loop.bat
