name: AkatsukiRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка Ngrok.
      run: |
        sudo wget https://www.vpn.net/installers/logmein-hamachi_2.1.0.203-1_amd64.deb -O hamachi.deb
    - name: Загрузка программ.
      run: |
        ls
        ls
    - name: Загрузка Ngrok файла.
      run: sudo dpkg -i hamachi.deb
    - name: Подключение к учётной записи Ngrok.
      run: |
        sudo /etc/init.d/logmein-hamachi start
    - name: Подключение к CPU 2 - 7 ГБ оперативной памяти - 256 SSD.
      run: |
        sudo hamachi logout
        sudo hamachi login
        sudo hamachi set-nick raspberry
    - name: Сделано успешно! Вы можете закрыть вкладку.
      run: cmd /c loop.bat
